#!/bin/sh -u

files=${*-*.o}
status=0

for f in $files; do
    bad=`
	nm $f |
	awk '$3 !~ /^speedy/ && $3 != "main" && $3 != "xs_init" && ($2 == "T" || $2 == "C" || $2 == "D") {
	    print $3;
	}'
    `
    if test "$bad" != ""; then
	echo Error in ${f}: exporting symbols $bad
	status=1
    fi
done
exit $status
